[package]
name = "that-guynamedbrian/signal"
description = "A simple, fast signal module"
license = "MIT"
authors = ["that-guynamedbrian/kobayashi"]
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]